# Generated by Django 5.2.5 on 2025-11-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='queue',
            name='max_slots',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='queue',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
