# Generated by Django 5.2.5 on 2025-11-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_queue_is_active_queue_max_slots_queue_scheduled_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('ready', 'Ready'), ('completed', 'Completed'), ('no_show', 'No Show')], default='waiting', max_length=24),
        ),
    ]
