# Generated by Django 5.2.5 on 2025-12-12 19:11

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_queue_options_customuser_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=main.models.generate_room_id, editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
