# Generated by Django 5.2.5 on 2025-12-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_customuser_phone_remove_customuser_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueentry',
            name='queue',
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['event_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
